// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_sidebar)
QT_DECLARE_EXTERN_RESOURCE(qmake_Sidebar)
QT_DECLARE_EXTERN_RESOURCE(sidebar_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Sidebar)

class SidebarPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    SidebarPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Sidebar)
QT_KEEP_RESOURCE(qmlcache_sidebar)
QT_KEEP_RESOURCE(qmake_Sidebar)
QT_KEEP_RESOURCE(sidebar_raw_qml_0)
    }
};



#include "sidebarplugin_SidebarPlugin.moc"
